### ISSUE TITLE
Too many files open error

### ISSUE THREAD

**Issue by sarandafl** [amietn/vcsi#41]
When not specifying a single file, but rather a whole directory, the following exception is raised:
```
Traceback (most recent call last):
  File "/usr/local/bin/vcsi", line 9, in <module>
    load_entry_point('vcsi==6', 'console_scripts', 'vcsi')()
  File "/usr/local/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/__init__.py", line 3, in main
  File "/usr/local/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/vcsi.py", line 1297, in main
  File "/usr/local/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/vcsi.py", line 1315, in process_file
  File "/usr/local/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/vcsi.py", line 79, in __init__
  File "/usr/local/lib/python3.5/site-packages/vcsi-6-py3.5.egg/vcsi/vcsi.py", line 105, in probe_media
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1454, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

```

I am not sure if this is OS X specific, but it still happens after I raise the max amount of open files and processes allowed. This happens after processing just 5 videos.

**Comment by amietn** [comment]
Thanks for reporting. Files were not being closed.
