### ISSUE TITLE
vcsi generating "empty" (zero size) temporary images and then fails

### ISSUE THREAD

**Issue by GuguKatze** [amietn/vcsi#82]
The temporary images vcsi complains about got a size of 0 bytes.

`
root@DESKTOP-45D2TDM:/tmp# /usr/local/bin/vcsi /tmp/ellamilano_2020-05-11_17-06-03.mp4 -t -w 1920 -g 4x4 --background-color 000000 --start-delay-percent 1 --end-delay-percent 1 --metadata-position top --grid-horizontal-spacing 1 --grid-vertical-spacing 1 --timestamp-font "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf" --timestamp-font-size 24 --metadata-font "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" --metadata-font-size 24 --timestamp-format '{H}:{M}' --timestamp-vertical-padding 5 -vvv -v -v -v --format jpg -o /tmp/ellamilano_2020-05-11_17-06-03.jpg
Considering /tmp/ellamilano_2020-05-11_17-06-03.mp4...
Processing /tmp/ellamilano_2020-05-11_17-06-03.mp4...
ellamilano_2020-05-11_17-06-03.mp4
1280x720
1280x720
13:37
300.4 MiB
Traceback (most recent call last):
  File "/usr/local/bin/vcsi", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vcsi/__init__.py", line 3, in main
    vcsi.vcsi.main()
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 1518, in main
    process_file(filename, args)
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 1646, in process_file
    selected_frames, temp_frames = select_sharpest_images(media_info, media_capture, args)
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 658, in select_sharpest_images
    frame = do_capture(timestamp_tuple, desired_size[0], desired_size[1], suffix, args)
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 618, in do_capture
    blurriness = media_capture.compute_blurriness(filename)
  File "/usr/local/lib/python3.6/dist-packages/vcsi/vcsi.py", line 514, in compute_blurriness
    i = Image.open(image_path)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmp7rwh5hj3.png'
`

**Comment by xanadu6291** [comment]
I had the same issue. In my case, by setting --end-delay-percent option to 20 fixed the issue...
