### ISSUE TITLE
"cannot identify image file %r" %

### ISSUE THREAD

**Issue by jhemmmm** [amietn/vcsi#86]
I have been using vcsi for a long time. And i'd like to fix this issue.

> The command "/usr/bin/vcsi /home/402c5ce63718915e685fa897dd5569a8 --grid-horizontal-spacing 0 --grid-vertical-spacing 0 -fast --quality 80 -w 852 -g 4x4 --metadata-position hidden -o /home/402c5ce63718915e685fa897dd5569a8poster_output.jpg" failed.
> 
> Exit Code: 1(General error)
> 
> Working directory: /home/apivcsi
> 
> Output:
> ================
> Processing /home/402c5ce63718915e685fa897dd5569a8...
> Sampling... 1/16
> Sampling... 2/16
> Sampling... 3/16
> Sampling... 4/16
> Sampling... 5/16
> Sampling... 6/16
> Sampling... 7/16
> Sampling... 8/16
> 
> Error Output:
> ================
> Traceback (most recent call last):
>   File "/usr/bin/vcsi", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/site-packages/vcsi/__init__.py", line 3, in main
>     vcsi.vcsi.main()
>   File "/usr/local/lib/python3.6/site-packages/vcsi/vcsi.py", line 1518, in main
>     process_file(filename, args)
>   File "/usr/local/lib/python3.6/site-packages/vcsi/vcsi.py", line 1646, in process_file
>     selected_frames, temp_frames = select_sharpest_images(media_info, media_capture, args)
>   File "/usr/local/lib/python3.6/site-packages/vcsi/vcsi.py", line 658, in select_sharpest_images
>     frame = do_capture(timestamp_tuple, desired_size[0], desired_size[1], suffix, args)
>   File "/usr/local/lib/python3.6/site-packages/vcsi/vcsi.py", line 618, in do_capture
>     blurriness = media_capture.compute_blurriness(filename)
>   File "/usr/local/lib/python3.6/site-packages/vcsi/vcsi.py", line 514, in compute_blurriness
>     i = Image.open(image_path)
>   File "/usr/local/lib64/python3.6/site-packages/PIL/Image.py", line 2896, in open
>     "cannot identify image file %r" % (filename if filename else fp)
> PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmpi_8t0e0v.png'

**Comment by derberherbert** [comment]
Had the same issue. The temp file was 0 KB big. 
Calling ffmpeg from the command line revealed a broken ffmpeg installation. Reinstalled ffmpeg, confirmed it was executable without error and vcsi worked without errors again.

**Comment by jhemmmm** [comment]
Yes, ffmpeg works perfectly. I am using pre-build 
https://www.johnvansickle.com/

**Comment by Chaz6** [comment]
I am experiencing this too. This is especially annoying because when I pass a list of files and it stops halfway through (I usually use it like this `$ vcsi folder/**/*.mkv` so I have to manually remove the file causing the issue, re-run vcsi, then put the file back. That said, thanks for working on vcsi!

**Comment by user222224** [comment]
I occasionally run into this error as well, it would be nice if vcsi would instead of failing completely just add a placeholder image for the erroneous frames, at least in the case if there's already a couple of frames that were calculated successfully.

A tip for those running into this issue when processing batches of files, you can add the --ignore-errors commandline switch which will cause vcsi to not stop the batch instead it will output a warning and skip to the next file in the batch.

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Kensingtonn, @Efficient365678, @grmpyninja, @WesVleuten, @lotz84, @Chxpz, @danigorbaciov, @aKesav, @JoeCool02, @MartinMaritim, @rizedr, @rishabh-malik, @blaxill, @xilaraux, @tangojo, @cchriso, @Vendran, @tiocnft, @weidutech, @denisglotov, @lyuich, @VNAPNIC, @P-Odziomek, @vagrant1991, @0xAWM, @cryptid11, @9h0std09, @shahankhatch, @La-Ka, @sikaffy27, @marksman0011, @omnionix, @ugoarzur, @Alfie, @zeekay, @Picnic6868778, @darwinshameran, @b33l238u8, @jdg, @cnasikas, @KenatSF, @hexcowboy, @misoobu, @eversinc33, @ofek, @Hangyul-Son, @inf0s3cN00b, @sinardyas, @ssetzer, @zdrift3r

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @porkchop, @chu4nx, @ledboot, @greysonn, @dolinh8757785, @Raven34152, @goean, @bberzhou, @oddcod3, @blokboy, @dglowinski, @We5ter, @Ethan-ahnlabio, @kylebakerio, @0xCRC32, @Troublor, @Mussel222, @mutalisk999, @youngqqcn, @anysoft, @Earthnook, @ShangzhiXu, @byte-ramble, @ogli324, @hieple7985, @Market2199897, @mratsim, @yippee-ki-yay, @nicchongwb, @giovannimorlin, @marco-fp, @waheya, @angelocastellani, @MenelikV, @oieduardorabelo, @thibault-lr, @fedot, @Disco276788, @tomo25, @wenweih, @neodaoist, @bch15, @Uncommon-Dev, @pmackay, @ysris, @ChristianBako, @xhyumiracle, @calenfretts, @ConstantinHvber, @tcode2k16
