### ISSUE TITLE
output path does not exist, causes vcsi to crash

### ISSUE THREAD

**Issue by connect192168** [amietn/vcsi#88]
my OS:
Windows 10 (build 2004, the latest one as of writing this)

my install process:
    confirming that the lastest version of Zeranoe's ffmpeg was installed and added to my path 
    pip install vcsi (that's it, i'm assuming that the pypi install instructions are correct and complete)

the vcsi command I used:
`vcsi -v -r -o test\Screens test\`

full command prompt text dump:
`T:\>pip install vcsi
Collecting vcsi
  Using cached vcsi-7.0.12-py3-none-any.whl (16 kB)
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting parsedatetime
  Using cached parsedatetime-2.6-py3-none-any.whl (42 kB)
Collecting numpy
  Using cached numpy-1.19.1-cp38-cp38-win_amd64.whl (13.0 MB)
Collecting pillow
  Using cached Pillow-7.2.0-cp38-cp38-win_amd64.whl (2.1 MB)
Collecting texttable
  Using cached texttable-1.6.2-py2.py3-none-any.whl (10 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl (16 kB)
Installing collected packages: MarkupSafe, jinja2, parsedatetime, numpy, pillow, texttable, vcsi
Successfully installed MarkupSafe-1.1.1 jinja2-2.11.2 numpy-1.19.1 parsedatetime-2.6 pillow-7.2.0 texttable-1.6.2 vcsi-7.0.12

T:\>vcsi -v -r -o test\Screens test\
Considering test\testfile.mp4...
Processing test\testfile.mp4...
testfile.mp4
720x400
711x400
42:45
412.5 MiB
Sampling... 16/16
Composing contact sheet...
Loading font...
Trying to load font: /usr/share/fonts/TTF/DejaVuSans-Bold.ttf
Trying to load font: /Library/Fonts/Arial Unicode.ttf
Falling back to default font.
Loading font...
Trying to load font: /usr/share/fonts/TTF/DejaVuSans.ttf
Trying to load font: /Library/Fonts/Arial Unicode.ttf
Falling back to default font.
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\PIL\Image.py", line 2138, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\vcsi.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\vcsi\__init__.py", line 3, in main
    vcsi.vcsi.main()
  File "c:\python38\lib\site-packages\vcsi\vcsi.py", line 1500, in main
    process_file(filepath, args)
  File "c:\python38\lib\site-packages\vcsi\vcsi.py", line 1651, in process_file
    is_save_successful = save_image(args, image, media_info, output_path)
  File "c:\python38\lib\site-packages\vcsi\vcsi.py", line 1047, in save_image
    image.save(output_path, optimize=True, quality=args.image_quality)
  File "c:\python38\lib\site-packages\PIL\Image.py", line 2140, in save
    raise ValueError("unknown file extension: {}".format(ext)) from e
ValueError: unknown file extension:

T:\>`

any help would be appreciated.

**Comment by connect192168** [comment]
amendment:
I booted up ubuntu for Windows subsystem Linux and installed vcsi via pip.
The same issue occurred (so there's a low chance that fonts are the issue).

another terminal text dump:
`
T:\>vcsi -g 5x12 --metadata-font-size 10 --metadata-font arial.ttf --timestamp-font-size 10 --timestamp-font arial.ttf -v -r -o test\Screens test
Considering test\testfile.mp4...
Processing test\testfile.mp4...
testfile.mp4
1280x720
1280x720
54:12
2.3 GiB
Sampling... 60/60
Composing contact sheet...
Loading font...
Loading font...
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\PIL\Image.py", line 2138, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\vcsi.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\vcsi\__init__.py", line 3, in main
    vcsi.vcsi.main()
  File "c:\python38\lib\site-packages\vcsi\vcsi.py", line 1500, in main
    process_file(filepath, args)
  File "c:\python38\lib\site-packages\vcsi\vcsi.py", line 1651, in process_file
    is_save_successful = save_image(args, image, media_info, output_path)
  File "c:\python38\lib\site-packages\vcsi\vcsi.py", line 1047, in save_image
    image.save(output_path, optimize=True, quality=args.image_quality)
  File "c:\python38\lib\site-packages\PIL\Image.py", line 2140, in save
    raise ValueError("unknown file extension: {}".format(ext)) from e
ValueError: unknown file extension:

T:\>
`

**Comment by FloPinguin** [comment]
I also got exactly this error message. Solution: The path in the -o parameter did not exist.

**Comment by connect192168** [comment]
Root cause can be reproduced on my end.
I manually created the folder and it worked fine.

**Comment by amietn** [comment]
I understand this is not an issue anymore. Feel free to reopen if needed.
